version: "2"

run:
  timeout: 5m
  skip-dirs:
    - internal/mocks

linters:
  enable:
    - revive
    - govet
    - staticcheck
    - unused
    - errcheck
    - ineffassign
    - unconvert
    - goconst
    - gocyclo
    - bodyclose
    - dogsled
    - durationcheck
    - errorlint
    - gocritic
    - gosec
    - makezero
    - misspell
    - nakedret
    - nestif
    - prealloc
    - unparam
    - whitespace
